spring:
  application:
    name: api-gateway

server:
  port: 8188

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8181/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.int}

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
zuul:
  routes:
    eureka-consumer: /eureka-consumer/**
    eureka-consumer-feign: /eureka-consumer-feign/**
